name: Release

on:
  release:
    types:
      - published

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          validate-wrappers: true

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload GitHub release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/libs/*.jar;!build/libs/*-sources.jar;!build/libs/*-dev.jar'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
