name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build with Gradle
      run: ./gradlew build
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Upload GitHub release
      uses: AButler/upload-release-assets@v3.0
      with:
        files: 'build/libs/*.jar;!build/libs/*-dev.jar'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
